site_name: 电子白板维护手册
site_url: https://tech-guide.su-gzno3ms.lty.one
copyright: 本站所有内容均在 <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh" rel="noopener noreferrer" target="_blank">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license" rel="noopener noreferrer" target="_blank">SATA</a> 协议条款下提供

nav:
  - 简介:
    - 概述: index.md

  - 日常维护:
    - 软件篇:
      - 面向 32 位操作系统用户的提示: daily-maintenance/software/notice-for-32bit-os.md
      - 电子白板: daily-maintenance/software/e-whiteboard.md
      - 输入法: daily-maintenance/software/input-method.md
      - 浏览器: daily-maintenance/software/internet-browser.md
      - Adobe Flash Player: daily-maintenance/software/flash.md
      - 多媒体: daily-maintenance/software/multimedia.md
      - 安全维护: daily-maintenance/software/security.md
      - 压缩文件管理: daily-maintenance/software/archived-files.md
    - 操作篇: 
      - 性能优化提示: daily-maintenance/operations/performance.md
      - 为触控操作优化设置: daily-maintenance/operations/optimize-for-touching-screen.md

  - 故障排除:
    - 清除系统内广告: troubleshooting/clean-ads.md
    - 微信 PC 版无法接收新信息时的解决方案 : troubleshooting/wechat-cannot-recieve-new-msg.md

theme:
  name: material
  language: zh
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: 暗色模式
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 亮色模式

repo_url: https://github.com/su-gzno3ms/tech-guide
repo_name: su-gzno3ms/tech-guide

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - toc: 
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}

plugins:
  - glightbox
